
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yashs
 */
public class Employee_info extends javax.swing.JFrame {

    /**
     * Creates new form Employee_info
     */
    public Employee_info() {
        initComponents();
        setSize(500,400);
        setTitle("Payroll Management System");
        getContentPane().setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        e2 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        t4 = new javax.swing.JButton();
        m1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Payroll Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Managing Employee Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 40));

        e2.setBackground(new java.awt.Color(255, 102, 0));
        e2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e2.setForeground(new java.awt.Color(0, 0, 102));
        e2.setText("Employee Attendance");
        e2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 330, 40));

        e3.setBackground(new java.awt.Color(255, 102, 0));
        e3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e3.setForeground(new java.awt.Color(0, 0, 102));
        e3.setText("Search Employee");
        e3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 330, 40));

        e1.setBackground(new java.awt.Color(255, 102, 0));
        e1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e1.setForeground(new java.awt.Color(0, 0, 102));
        e1.setText("Add Employee");
        e1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        e1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 330, 40));

        t4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        t4.setText("Manage Employee Information");
        t4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 330, 40));

        m1.setBackground(new java.awt.Color(255, 102, 0));
        m1.setForeground(new java.awt.Color(0, 0, 102));
        m1.setText("Main Menu");
        m1.setBorder(new javax.swing.border.MatteBorder(null));
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        this.setVisible(false);
        new Employee_Form().setVisible(true);
    }//GEN-LAST:event_e1ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_m1ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
       this.setVisible(false);
        new Employee_search().setVisible(true);
    }//GEN-LAST:event_e3ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        this.setVisible(false);
        new EmployeeAttendance().setVisible(true);
    }//GEN-LAST:event_e2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton m1;
    private javax.swing.JButton t4;
    // End of variables declaration//GEN-END:variables
}
