

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yashs
 */
public class PayStub extends javax.swing.JFrame {

    /**
     * Creates new form PayStub
     */
    java.sql.Connection con;
    PreparedStatement ps;
    public PayStub() {
        initComponents();
        setTitle("Payroll Management System");
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payrollmangement","root","");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null,ee);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tds = new javax.swing.JLabel();
        emp1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        basicsal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mon1 = new javax.swing.JLabel();
        finalsal = new javax.swing.JLabel();
        leaves = new javax.swing.JLabel();
        da = new javax.swing.JLabel();
        esi = new javax.swing.JLabel();
        pf = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 50));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setSize(new java.awt.Dimension(840, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Emp- Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 30));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 30));

        c1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 0, 0));
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 30));

        c2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 0, 0));
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 110, 30));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 120, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pay Stub");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Net Pay");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 750, 20));

        tds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tds.setText("TDS");
        jPanel1.add(tds, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 60, -1));

        emp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emp1.setText("Emp - Id");
        jPanel1.add(emp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        basicsal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        basicsal.setText("Basic Salary");
        jPanel1.add(basicsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Employee Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 750, 20));

        mon1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mon1.setText("Month");
        jPanel1.add(mon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 50, -1));

        finalsal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        finalsal.setText("Total Pay");
        jPanel1.add(finalsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        leaves.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        leaves.setText("Total Leaves");
        jPanel1.add(leaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        da.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        da.setText("DA");
        jPanel1.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        esi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        esi.setText("Esi");
        jPanel1.add(esi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 50, -1));

        pf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pf.setText("PF");
        jPanel1.add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 50, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Deductions");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 750, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Emp - Id");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Basic Salary");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Total Leaves");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("DA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Esi");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 50, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("PF");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("TDS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 60, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Total Pay");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Month");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
    Object month = c1.getSelectedItem();
    Object year = c2.getSelectedItem();
    
    // Establish the database connection (replace "your_connection_info" with actual connection details)
    
    
    PreparedStatement ps = con.prepareStatement("select * from salary where empid=? and month=? and year=?");
    ps.setString(1,this.t1.getText());
    ps.setObject(2, month);
    ps.setObject(3, year);
    
    // Prepare and execute a SQL query to fetch data from the "attendance" table
    ResultSet rs = ps.executeQuery();
    
    while (rs.next()) {
        // Extract data from the ResultSet and add it to the JTable
        
            emp1.setText(rs.getString("empid"));
            name.setText(rs.getString("name"));
            mon1.setText(rs.getString("month"));
            leaves.setText(rs.getString("total_leave"));
            
            basicsal.setText(rs.getString("basic_salary"));
            da.setText(rs.getString("da"));
            esi.setText(rs.getString("esi"));
            pf.setText(rs.getString("pf"));
            tds.setText(rs.getString("tds_Tax"));
            finalsal.setText(rs.getString("total_salary"));
           
        
    }
    
    // Close the ResultSet, PreparedStatement, and the database connection
    rs.close();
    ps.close();
    con.close();
} catch (Exception ex) {
         JOptionPane.showMessageDialog(null, ex);
        System.out.println(ex);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayStub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayStub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayStub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayStub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayStub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicsal;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JLabel da;
    private javax.swing.JLabel emp1;
    private javax.swing.JLabel esi;
    private javax.swing.JLabel finalsal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leaves;
    private javax.swing.JLabel mon1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pf;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel tds;
    // End of variables declaration//GEN-END:variables
}
